# Generated by Django 3.0.10 on 2022-04-16 03:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppPlanificacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distaves',
            name='id_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppPlanificacion.Planificaciones'),
        ),
        migrations.AlterField(
            model_name='distcomercial',
            name='id_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppPlanificacion.Planificaciones'),
        ),
        migrations.AlterField(
            model_name='distfamilia',
            name='id_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppPlanificacion.Planificaciones'),
        ),
    ]
